In [4]:
import numpy as np
import pandas as pd

In [5]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [8]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movies=movies.merge(credits,on="title")

In [14]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
#genres
#id
#keywords
#title
#overview
#cast
#crew
movies[["movie_id","title","overview","genres","keywords","cast","crew"]]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [17]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [19]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [21]:
movies.dropna(inplace=True)

In [22]:
movies.duplicated().sum()

np.int64(0)

In [23]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#["Action","Advrnture","FFantacy","SciFi"]

In [35]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [36]:
movies["genres"].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4779                                         [Comedy]
4787                                [Comedy, Romance]
4797                                         [Horror]
4802               [Science Fiction, Drama, Thriller]
4807                                               []
Name: genres, Length: 1494, dtype: object

In [38]:
movies["keywords"]=movies["keywords"].apply(convert)

In [46]:
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
           L.append(i["name"])
           counter+=1
        else:
           break
    return L

In [48]:
movies["cast"].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4779       [Brian O'Halloran, Jeff Anderson, Jason Mewes]
4787         [Suzi Lorraine, Jared Degado, Heather Dorff]
4797    [Michael Parle, Emma Eliza Regan, Patrick O'Do...
4802        [Shane Carruth, David Sullivan, Casey Gooden]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
Name: cast, Length: 1494, dtype: object

In [49]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [50]:
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [52]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
           L.append(i["name"])
           break
    return L

In [53]:
movies["crew"].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4779          [Kevin Smith]
4787         [Travis Legge]
4797        [Ivan Kavanagh]
4802        [Shane Carruth]
4807          [Daniel Hsia]
Name: crew, Length: 1494, dtype: object

In [54]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [55]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [56]:
movies["overview"]=movies["overview"].apply(lambda x:x.split())

In [57]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [58]:
movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ",'') for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ",'') for i in x])
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ",'') for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ",'') for i in x])

In [59]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,300000000,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,245000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.sonypictures.com/movies/spectre/,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",en,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,250000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.thedarkknightrises.com/,49026,"[dccomics, crimefighter, terrorist, secretiden...",en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,260000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://movies.disney.com/john-carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...",en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [60]:
movies["tags"]=movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [61]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew,tags
0,237000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,300000000,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Captain, Barbossa,, long, believed, to, be, d..."
2,245000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.sonypictures.com/movies/spectre/,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",en,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[A, cryptic, message, from, Bond’s, past, send..."
3,250000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.thedarkknightrises.com/,49026,"[dccomics, crimefighter, terrorist, secretiden...",en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Following, the, death, of, District, Attorney..."
4,260000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://movies.disney.com/john-carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...",en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[John, Carter, is, a, war-weary,, former, mili..."

In [62]:
new_df=movies[["movie_id","title","tags"]]

In [64]:
new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_41472\1804341217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

In [65]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [77]:
import nltk

In [78]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [82]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [84]:
new_df["tags"]=new_df["tags"].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_41472\1027202188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(stem)

In [66]:
new_df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " S c i e n c e  F i c t i o n " } ] cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " J a k e  S u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " S a m  W o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " N e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " Z o e  S a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " D r .  G r a c e  A u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " S i g o u r n e y  W e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " C o l .  Q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " S t e p h e n  L a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " T r u d y  C h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " M i c h e l l e  R o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " S e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " G i o v a n n i  R i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " N o r m  S p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " J o e l  D a v i d  M o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " M o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " C C H  P o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " E y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " W e s  S t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " T s u \' T e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " L a z  A l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " D r .  M a x  P a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " D i l e e p  R a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " L y l e  W a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " M a t t  G e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " P r i v a t e  F i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " S e a n  A n t h o n y  M o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " C r y o  V a u l t  M e d  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " J a s o n  W h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " V e n t u r e  S t a r  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " S c o t t  L a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " L o c k  U p  T r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " K e l l y  K i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " S h u t t l e  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " J a m e s  P a t r i c k  P i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " S h u t t l e  C o - P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " S e a n  P a t r i c k  M u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " S h u t t l e  C r e w  C h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " P e t e r  D i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " T r a c t o r  O p e r a t o r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " K e v i n  D o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  P i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " K e l s o n  H e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  G u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " D a v i d  V a n  H o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " D r a g o n  G u n s h i p  N a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " J a c o b  T o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " S u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " M i c h a e l  B l a i n - R o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " S u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " J o n  C u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " L u k e  H a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " A m b i e n t  R o o m  T e c h  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " W o o d y  S c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " H o r s e  C l a n  L e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " P e t e r  M e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " L i n k  R o o m  T e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " S o n i a  Y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r  /  T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " J a h n e l  C u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " B a s k e t b a l l  A v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " I l r a m  C h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " N a \' v i  C h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " K y l a  W a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " L i s a  R o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " D e b r a  W i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " C h r i s  M a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " T a y l o r  K i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " J o d i e  L a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " J u l i e  L a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " C u l l e n  B .  M a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " J o s e p h  B r a d y  M a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " F r a n k i e  T o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " A u s t i n  W i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " S a r a  W i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " T r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " T a m i c a  W a s h i n g t o n - M i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " L u c y  B r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " N a t h a n  M e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " G e r r y  B l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " M a t t h e w  C h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " P a u l  Y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " O p  C e n t e r  D u t y  O f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " W r a y  W i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " O p  C e n t e r  S t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " J a m e s  G a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " M e l v i n  L e n o  C l a r k  I I I " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " C a r v o n  F u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " B r a n d o n  J e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " M i c a h  M o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " H a n n i y a h  M u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " C h r i s t o p h e r  N o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " C h r i s t a  O l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " A p r i l  M a r i e  T h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " D a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " B r a v i t a  A .  T h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " M i n i n g  C h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " C o l i n  B l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " V e t e r a n  M i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " M i k e  B o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " R i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e " :  " M a t t  C l a y t o n " ,  " o r d e r " :  6 2 } ,  { " c a s t _ i d " :  8 4 ,  " c h a r a c t e r " :  " N a v \' i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " ,  " g e n d e r " :  1 ,  " i d " :  1 4 7 8 9 8 ,  " n a m e " :  " N i c o l e  D i o n n e " ,  " o r d e r " :  6 3 } ,  { " c a s t _ i d " :  8 5 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 0 ,  " n a m e " :  " J a m i e  H a r r i s o n " ,  " o r d e r " :  6 4 } ,  { " c a s t _ i d " :  8 6 ,  " c h a r a c t e r " :  " T r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 1 ,  " n a m e " :  " A l l a n  H e n r y " ,  " o r d e r " :  6 5 } ,  { " c a s t _ i d " :  8 7 ,  " c h a r a c t e r " :  " G r o u n d  T e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " ,  " g e n d e r " :  2 

In [67]:
new_df["tags"][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. [ { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ] ocean drugabuse exoticisland eastindiatradingcompany loveofone\'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger [ { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " C a p t a i n  J a c k  S p a r r o w " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 0 d " ,  " g e n d e r " :  2 ,  " i d " :  8 5 ,  " n a m e " :  " J o h n n y  D e p p " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " W i l l  T u r n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 1 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 1 4 ,  " n a m e " :  " O r l a n d o  B l o o m " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  6 ,  " c h a r a c t e r " :  " E l i z a b e t h  S w a n n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 1 5 " ,  " g e n d e r " :  1 ,  " i d " :  1 1 6 ,  " n a m e " :  " K e i r a  K n i g h t l e y " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " W i l l i a m  \\ " B o o t s t r a p  B i l l \\ "  T u r n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 2 d " ,  " g e n d e r " :  2 ,  " i d " :  1 6 4 0 ,  " n a m e " :  " S t e l l a n  S k a r s g \\ u 0 0 e 5 r d " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " C a p t a i n  S a o  F e n g " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 2 5 " ,  " g e n d e r " :  2 ,  " i d " :  1 6 1 9 ,  " n a m e " :  " C h o w  Y u n - f a t " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " C a p t a i n  D a v y  J o n e s " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 2 1 " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 0 ,  " n a m e " :  " B i l l  N i g h y " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " C a p t a i n  H e c t o r  B a r b o s s a " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 1 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 1 8 ,  " n a m e " :  " G e o f f r e y  R u s h " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  1 4 ,  " c h a r a c t e r " :  " A d m i r a l  J a m e s  N o r r i n g t o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 3 5 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 0 9 ,  " n a m e " :  " J a c k  D a v e n p o r t " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " J o s h a m e e  G i b b s " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 3 1 " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 9 ,  " n a m e " :  " K e v i n  M c N a l l y " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " L o r d  C u t l e r  B e c k e t t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 2 9 " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 1 ,  " n a m e " :  " T o m  H o l l a n d e r " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 9 ,  " c h a r a c t e r " :  " T i a  D a l m a " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 4 9 " ,  " g e n d e r " :  1 ,  " i d " :  2 0 3 8 ,  " n a m e " :  " N a o m i e  H a r r i s " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " G o v e r n o r  W e a t h e r b y  S w a n n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 1 d " ,  " g e n d e r " :  2 ,  " i d " :  3 7 8 ,  " n a m e " :  " J o n a t h a n  P r y c e " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " C a p t a i n  T e a g u e  S p a r r o w " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 b 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 4 3 0 ,  " n a m e " :  " K e i t h  R i c h a r d s " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  1 6 ,  " c h a r a c t e r " :  " P i n t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 3 d " ,  " g e n d e r " :  2 ,  " i d " :  1 7 1 0 ,  " n a m e " :  " L e e  A r e n b e r g " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  1 5 ,  " c h a r a c t e r " :  " R a g e t t i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 3 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 1 1 ,  " n a m e " :  " M a c k e n z i e  C r o o k " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  1 8 ,  " c h a r a c t e r " :  " L i e u t e n a n t  T h e o d o r e  G r o v e s " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 4 5 " ,  " g e n d e r " :  2 ,  " i d " :  4 0 3 1 ,  " n a m e " :  " G r e g  E l l i s " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " C o t t o n " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d 2 e c 3 a 3 6 8 1 a 0 1 0 0 5 b 5 c " ,  " g e n d e r " :  2 ,  " i d " :  1 7 1 5 ,  " n a m e " :  " D a v i d  B a i l i e " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  1 7 ,  " c h a r a c t e r " :  " M a r t y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 4 1 " ,  " g e n d e r " :  2 ,  " i d " :  4 0 3 0 ,  " n a m e " :  " M a r t i n  K l e b b a " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " I a n  M e r c e r " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d 7 8 c 3 a 3 6 8 0 8 b 9 0 0 b f 4 f " ,  " g e n d e r " :  0 ,  " i d " :  9 3 9 ,  " n a m e " :  " D a v i d  S c h o f i e l d " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " S c a r l e t t " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 e c 5 c 3 a 3 6 8 1 a 5 0 0 0 5 8 5 5 " ,  " g e n d e r " :  1 ,  " i d " :  2 4 5 0 ,  " n a m e " :  " L a u r e n  M a h e r " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " G i s e l l e " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 e d 6 9 2 5 1 4 1 2 3 f 5 0 0 5 6 3 5 " ,  " g e n d e r " :  1 ,  " i d " :  2 4 5 2 ,  " n a m e " :  " V a n e s s a  B r a n c h " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " M u l l r o y " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d b 2 c 3 a 3 6 8 1 a 0 1 0 0 5 b c 7 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 1 4 ,  " n a m e " :  " A n g u s  B a r n e t t " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " M u r t o g g " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d a 1 9 2 5 1 4 1 1 8 f 7 0 0 6 0 0 8 " ,  " g e n d e r " :  0 ,  " i d " :  1 7 1 3 ,  " n a m e " :  " G i l e s  N e w " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " T a i  H u a n g " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d 8 e c 3 a 3 6 8 1 a 0 1 0 0 5 b a b " ,  " g e n d e r " :  2 ,  " i d " :  2 2 0 7 5 ,  " n a m e " :  " R e g g i e  L e e " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " H e n r y  T u r n e r " ,  " c r e d i t _ i d " :  " 5 7 e 2 9 1 1 9 9 2 5 1 4 1 1 5 1 1 0 0 a 6 c c " ,  " g e n d e r " :  2 ,  " i d " :  6 1 2 5 9 ,  " n a m e " :  " D o m i n i c  S c o t t  K a y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " M i s t r e s s  C h i n g " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 b d " ,  " g e n d e r " :  1 ,  " i d " :  3 3 5 0 0 ,  " n a m e " :  " T a k a y o  F i s c h e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " L i e u t e n a n t  G r e i t z e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 c 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 2 2 4 1 4 9 ,  " n a m e " :  " D a v i d  M e u n i e r " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " H a d r a s " ,  " c r e d i t _ i d " :  " 5 6 d 1 8 7 1 c 9 2 5 1 4 1 7 4 6 8 0 0 1 0 c f " ,  " g e n d e r " :  2 ,  " i d " :  4 2 9 4 0 1 ,  " n a m e " :  " H o - K w a n  T s e " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " C l a c k e r " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d 4 b 9 2 5 1 4 1 2 5 7 1 0 0 5 5 c b " ,  " g e n d e r " :  0 ,  " i d " :  1 1 2 3 ,  " n a m e " :  " A n d y  B e c k w i t h " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " P e n r o d " ,  " c r e d i t _ i d " :  " 5 6 e c 8 c 1 4 c 3 a 3 6 8 2 2 6 0 0 0 3 c 5 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 5 6 1 1 7 ,  " n a m e " :  " P e t e r  D o n a l d  B a d a l a m e n t i  I I " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " C o t t o n \' s  P a r r o t  ( v o i c e ) " ,  " c r e d i t _ i d " :  " 5 7 e 2 8 d c c 9 2 5 1 4 1 2 4 6 3 0 0 5 6 7 8 " ,  " g e n d e r " :  2 ,  " i d " :  2 1 7 0 0 ,  " n a m e " :  " C h r i s t o p h e r  S .  C a p p " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " C a p t a i n  T e a g u e " ,  " c r e d i t _ i d " :  " 5 8 b c 2 a 3 7 c 3 a 3 6 8 6 6 3 0 0 3 7 4 0 b " ,  " g e n d e r " :  2 ,  " i d " :  1 4 3 0 ,  " n a m e " :  " K e i t h  R i c h a r d s " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " C a p t a i n  J o c a r d " ,  " c r e d i t _ i d " :  " 5 8 b c 2 a 8 e 9 2 5 1 4 1 6 0 9 e 0 3 a 1 7 9 " ,  " g e n d e r " :  2 ,  " i d " :  2 6 0 3 ,  " n a m e " :  " H a k e e m  K a e - K a z i m " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " C a p t a i n  A m m a n d " ,  " c r e d i t _ i d " :  " 5 8 e 2 a 2 1 a c 3 a 3 6 8 7 2 a f 0 0 f 9 c 2 " ,  " g e n d e r " :  0 ,  " i d " :  7 0 5 7 7 ,  " n a m e " :  " G h a s s a n  M a s s o u d " ,  " o r d e r " :  3 3 } ] [ { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 9 " ,  " d e p a r t m e n t " :  " C a m e r a " ,  " g e n d e r " :  2 ,  " i d " :  1 2 0 ,  " j o b " :  " D i r e c t o r  o f  P h o t o g r a p h y " ,  " n a m e " :  " D a r i u s z  W o l s k i " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 4 f d " ,  " d e p a r t m e n t " :  " D i r e c t i n g " ,  " g e n d e r " :  2 ,  " i d " :  1 7 0 4 ,  " j o b " :  " D i r e c t o r " ,  " n a m e " :  " G o r e  V e r b i n s k i " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 4 f " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  2 ,  " i d " :  7 7 0 ,  " j o b " :  " P r o d u c e r " ,  " n a m e " :  " J e r r y  B r u c k h e i m e r " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 0 3 " ,  " d e p a r t m e n t " :  " W r i t i n g " ,  " g e n d e r " :  2 ,  " i d " :  1 7 0 5 ,  " j o b " :  " S c r e e n p l a y " ,  " n a m e " :  " T e d  E l l i o t t " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 0 9 " ,  " d e p a r t m e n t " :  " W r i t i n g " ,  " g e n d e r " :  2 ,  " i d " :  1 7 0 6 ,  " j o b " :  " S c r e e n p l a y " ,  " n a m e " :  " T e r r y  R o s s i o " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 f " ,  " d e p a r t m e n t " :  " E d i t i n g " ,  " g e n d e r " :  0 ,  " i d " :  1 7 2 1 ,  " j o b " :  " E d i t o r " ,  " n a m e " :  " S t e p h e n  E .  R i v k i n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 8 5 " ,  " d e p a r t m e n t " :  " E d i t i n g " ,  " g e n d e r " :  2 ,  " i d " :  1 7 2 2 ,  " j o b " :  " E d i t o r " ,  " n a m e " :  " C r a i g  W o o d " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 3 " ,  " d e p a r t m e n t " :  " S o u n d " ,  " g e n d e r " :  2 ,  " i d " :  9 4 7 ,  " j o b " :  " O r i g i n a l  M u s i c  C o m p o s e r " ,  " n a m e " :  " H a n s  Z i m m e r " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 5 5 " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 4 ,  " j o b " :  " E x e c u t i v e  P r o d u c e r " ,  " n a m e " :  " M i k e  S t e n s o n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 1 " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 5 ,  " j o b " :  " P r o d u c e r " ,  " n a m e " :  " E r i c  M c L e o d " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 5 b " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  2 ,  " i d " :  2 4 4 6 ,  " j o b " :  " P r o d u c e r " ,  " n a m e " :  " C h a d  O m a n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 7 " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  0 ,  " i d " :  2 4 4 7 ,  " j o b " :  " P r o d u c e r " ,  " n a m e " :  " P e t e r  K o h n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 d " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  0 ,  " i d " :  2 4 4 8 ,  " j o b " :  " P r o d u c e r " ,  " n a m e " :  " P a t  S a n d s t o n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 8 b " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  1 ,  " i d " :  2 2 1 5 ,  " j o b " :  " C a s t i n g " ,  " n a m e " :  " D e n i s e  C h a m i a n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 7 " ,  " d e p a r t m e n t " :  " A r t " ,  " g e n d e r " :  2 ,  " i d " :  1 2 2 6 ,  " j o b " :  " P r o d u c t i o n  D e s i g n " ,  " n a m e " :  " R i c k  H e i n r i c h s " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 d " ,  " d e p a r t m e n t " :  " A r t " ,  " g e n d e r " :  2 ,  " i d " :  5 5 3 ,  " j o b " :  " A r t  D i r e c t i o n " ,  " n a m e " :  " J o h n  D e x t e r " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 1 " ,  " d e p a r t m e n t " :  " P r o d u c t i o n " ,  " g e n d e r " :  1 ,  " i d " :  3 3 1 1 ,  " j o b " :  " C a s t i n g " ,  " n a m e " :  " P r i s c i l l a  J o h n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a 3 " ,  " d e p a r t m e n t " :  " A r t " ,  " g e n d e r " :  1 ,  " i d " :  4 0 3 2 ,  " j o b " :  " S e t  D e c o r a t i o n " ,  " n a m e " :  " C h e r y l  C a r a s i k " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a 9 " ,  " d e p a r t m e n t " :  " C o s t u m e  &  M a k e - U p " ,  " g e n d e r " :  0 ,  " i d " :  4 0 3 3 ,  " j o b " :  " C o s t u m e  D e s i g n " ,  " n a m e " :  " L i z  D a n n " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a f " ,  " d e p a r t m e n t " :  " C o s t u m e  &  M a k e - U p " ,  " g e n d e r " :  1 ,  " i d " :  4 0 3 4 ,  " j o b " :  " C o s t u m e  D e s i g n " ,  " n a m e " :  " P e n n y  R o s e " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 c e 8 c 3 a 3 6 8 6 a 5 3 0 0 0 d 8 b " ,  " d e p a r t m e n t " :  " S o u n d " ,  " g e n d e r " :  2 ,  " i d " :  5 1 3 2 ,  " j o b " :  " M u s i c  S u p e r v i s o r " ,  " n a m e " :  " B o b  B a d a m i " } ,  { " c r e d i t _ i d " :  " 5 5 9 9 3 c 1 5 c 3 a 3 6 8 5 5 d b 0 0 2 f 3 3 " ,  " d e p a r t m e n t " :  " A r t " ,  " g e n d e r " :  2 ,  " i d " :  1 4 6 4 3 9 ,  " j o b " :  " C o n c e p t u a l  D e s i g n " ,  " n a m e " :  " J a m e s  W a r d  B y r k i t " } ,  { " c r e d i t _ i d " :  " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 b 9 " ,  " d e p a r t m e n t " :  " C o s t u m e  &  M a k e - U p " ,  " g e n d e r " :  1 ,  " i d " :  4 0 6 2 0 4 ,  " j o b " :  " M a k e u p  D e p a r t m e n t  H e a d " ,  " n a m e " :  " V e  N e i l l " } ,  { " c r e d i t _ i d " :  " 5 6 e 4 7 f 7 8 9 2 5 1 4 1 3 2 6 9 0 0 1 7 b d " ,  " d e p a r t m e n t " :  " C r e w " ,  " g e n d e r " :  2 ,  " i d " :  1 2 5 9 5 1 6 ,  " j o b " :  " S t u n t s " ,  " n a m e " :  " J o h n  D i x o n " } ,  { " c r e d i t _ i d " :  " 5 7 4 0 b e 6 3 9 2 5 1 4 1 6 5 9 7 0 0 0 8 4 9 " ,  " d e p a r t m e n t " :  " C r e w " ,  " g e n d e r " :  0 ,  " i d " :  1 3 3 6 7 1 6 ,  " j o b " :  " C G I  S u p e r v i s o r " ,  " n a m e " :  " D o t t i e  S t a r l i n g " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 c 6 3 9 2 5 1 4 1 2 f c 8 0 0 0 d c 1 " ,  " d e p a r t m e n t " :  " D i r e c t i n g " ,  " g e n d e r " :  1 ,  " i d " :  1 3 4 4 2 7 8 ,  " j o b " :  " S c r i p t  S u p e r v i s o r " ,  " n a m e " :  " P a m e l a  A l c h " } ,  { " c r e d i t _ i d " :  " 5 7 0 8 3 1 0 1 c 3 a 3 6 8 1 d 3 2 0 0 0 4 e 6 " ,  " d e p a r t m e n t " :  " C r e w " ,  " g e n d e r " :  0 ,  " i d " :  1 3 6 8 8 6 7 ,  " j o b " :  " S p e c i a l  E f f e c t s  C o o r d i n a t o r " ,  " n a m e " :  " A l l e n  H a l l " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 d 5 e c 3 a 3 6 8 6 a 6 2 0 0 0 d 4 a " ,  " d e p a r t m e n t " :  " S o u n d " ,  " g e n d e r " :  0 ,  " i d " :  1 3 6 8 8 8 4 ,  " j o b " :  " M u s i c  E d i t o r " ,  " n a m e " :  " M e l i s s a  M u i k " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 c 7 b 9 2 5 1 4 1 2 f d 4 0 0 0 e 0 7 " ,  " d e p a r t m e n t " :  " D i r e c t i n g " ,  " g e n d e r " :  1 ,  " i d " :  1 3 9 5 2 9 0 ,  " j o b " :  " S c r i p t  S u p e r v i s o r " ,  " n a m e " :  " S h a r r o n  R e y n o l d s " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 d 2 b c 3 a 3 6 8 6 a 5 3 0 0 0 d 9 b " ,  " d e p a r t m e n t " :  " S o u n d " ,  " g e n d e r " :  0 ,  " i d " :  1 3 9 9 3 2 7 ,  " j o b " :  " M u s i c  E d i t o r " ,  " n a m e " :  " B a r b a r a  M c D e r m o t t " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 c b 4 c 3 a 3 6 8 6 a 5 3 0 0 0 d 8 7 " ,  " d e p a r t m e n t " :  " D i r e c t i n g " ,  " g e n d e r " :  1 ,  " i d " :  1 4 0 0 7 3 8 ,  " j o b " :  " S c r i p t  S u p e r v i s o r " ,  " n a m e " :  " K a r e n  G o l d e n " } ,  { " c r e d i t _ i d " :  " 5 6 4 2 7 d 1 6 9 2 5 1 4 1 2 f d 4 0 0 0 e 2 3 " ,  " d e p a r t m e n t " :  " S o u n d " ,  " g e n d e r " :  0 ,  " i d " :  1 5 3 4 1 9 7 ,  " j o b " :  " M u s i c  E d i t o r " ,  " n a m e " :  " K a t i e  G r e a t h o u s e " } ]'

In [97]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

In [91]:
vectors= cv.fit_transform(new_df["tags"]).toarray()

In [92]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1494, 5000))

In [101]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [102]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [76]:
["loved","loving","love"]
["love","love","love"]

['love', 'love', 'love']

In [81]:
ps.stem("dancing")

'danc'

In [103]:
stem("In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization")

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civil'

In [149]:
from sklearn.metrics.pairwise import cosine_similarity

In [150]:
similarity=cosine_similarity(vectors)

In [151]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(579, np.float64(0.23249527748763857)),
 (331, np.float64(0.20718416498225883)),
 (423, np.float64(0.20056488422556007)),
 (1244, np.float64(0.18790823039834775)),
 (118, np.float64(0.16979054399120352))]

In [173]:
def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [174]:
recommend("Batman Begins")

(110, np.float64(0.3362963545672746))
(214, np.float64(0.3065696697424829))
(1259, np.float64(0.2951406680504776))
(50, np.float64(0.2729743416177752))
(290, np.float64(0.26997462357801943))

In [154]:
new_df.iloc[1216].title

'The Words'

In [162]:
import pickle

In [165]:
pickle.dump(new_df,open("movies.pkl","wb"))

In [167]:
new_df["title"].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Tin Can Man', 'Primer', 'Shanghai Calling'],
      shape=(1494,), dtype=object)

In [170]:
pickle.dump(new_df.to_dict(),open("movie_dict.pkl","wb"))

In [172]:
pickle.dump(similarity,open("similarity.pkl","wb"))